### ISSUE TITLE
No reaction on USB in Windows Host

### ISSUE THREAD

**Issue by Soily** [kmpm/rpi-usb-gadget#6]
Applying the script on a fresh raspbian image from today (02-05-2023), doesn't work. Means after connecting the Raspberry Pi 4 B to the host usb, and booting up, there's no reaction on the host-usb when observing either by device manager nor the usb-tree-view application.

I checked that all entries were made.
I checked lsmod that the driver is loaded.
I checked that the ip-address is shown in the usb0 device when using command "ifconfig".
I checked that the system services are properly executed.

**Comment by kmpm** [comment]
Works without a flaw from my Windows 11 computer to a RPI4 running Raspberry PI OS Lite (32-bit), flashed just now.
The only thing that I did that might affect things is that I installed all raspios updates before I ran the script.
The RPI turned up as another network interface in Windows Device Manager
![bild](https://user-images.githubusercontent.com/96618/216840711-6a8f02d5-a577-4f7b-bdab-7c95f6ad3acb.png)

I would like some more details so that I might be able to help you.
* What version of Windows 10/11 and 32/64 bit?
* What rasbian, lite or full desktop?
* 32 or 64 bit raspbian?
* have you verified that your USB-cable works with data transfer to something else? 
  It sounds strange but I have had issues where the cable was not up to spec.

**Comment by Soily** [comment]
Hello kmpm,

- I'm trying on Windows 10 and 64 Bit.
- Full Desktop
- 64-Bit
- I tried several usb-cables. Also a usb-c to usb-c (high speed) which is working for other data-devices without a flaw.

**Comment by Soily** [comment]
Hi again,

I found the root-cause. It's the housing. It has an extra usb-power connector and I though it's just a put-through connector. Sorry for the inconvenience.

**Comment by kmpm** [comment]
Good thing that you found it.
That's also one issue that I have run into before.

**Comment by Soily** [comment]
Hi kmpm,
thanks again for your quick help and I'm glad I was not the only one so stupid to check first for a physical connection :-).
Have a great time.
Kind Regards
Paddy
